[package]
name = "betterparsec-updater"
version.workspace = true
edition = "2024"
license.workspace = true

[lib]
name = "bp_updater"
path = "src/lib.rs"

[[bin]]
name = "betterparsec-updater"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
